### ISSUE TITLE
crash when making many layers

### ISSUE THREAD

**Issue by AnnieAtDataChemist** [terminusdb/terminusdb-store#13]
1. Download and install https://github.com/terminusdb/terminus_store_test

2. using SWI-Prolog 8.0.3, 
```
swipl run_test.pl
... banner elided...
?- go.
[settings(settings.db),count(-1),datafile(loaddata.csv),help(false)]
Segmentation fault (core dumped)
```

EXPECTED: no segmentation fault
OBSERVED: a fun and challenging core dump!

This is because we're making a whole mass of layers. 

tip: 

```
?- debug(test(_)).
```

will give more progress info.

**Comment by matko** [comment]
Since all the recursion should be gone now, this is hopefully resolved.

@AnnieAtDataChemist can you retry?

**Comment by rrooij** [comment]
Is resolved
