### ISSUE TITLE
Migrate from tokio 0.1 to 0.2

### ISSUE THREAD

**Issue by spl** [terminusdb/terminusdb-store#36]
At some point, I suppose `terminus-store` should be migrated from `tokio` 0.1 to 0.2.

See the following related items:
* https://users.rust-lang.org/t/failed-to-port-mononoke-to-tokio-0-2-experience-report/32478
* https://qiita.com/zenixls2/items/c594c87bf208a7094905
* https://www.ncameron.org/blog/migrating-a-crate-from-futures-0-1-to-0-3/

**Comment by matko** [comment]
It's definitely on the todo list, but unfortunately not on the short term due to other priorities. Doing the conversion will temporarily block all other development on the library and we simply can't do that right now.

As a rough estimate, I don't expect work on this to be able to commence until march.

**Comment by rrooij** [comment]
There is by the way a `tokio_compat` create which should make the transition to tokio 0.2 easier.

**Comment by spl** [comment]
Some additional things to keep in mind:

* The `bytes` interface changed between 0.4 (the dependency of `tokio-io` 0.1) and 0.5 (the dependency of `tokio` 0.2). (In #44, I avoided using `Buf` and `BufMut` to keep the usage of `bytes` simple with the `tokio` transition in mind.)
* Newer versions of `tokio` have methods like [`read_u64`](https://docs.rs/tokio/0.2.13/tokio/io/trait.AsyncReadExt.html#method.read_u64) and [`write_u64`](https://docs.rs/tokio/0.2.13/tokio/io/trait.AsyncWriteExt.html#method.write_u64) for big-endian numbers (https://github.com/tokio-rs/tokio/pull/1863).

**Comment by rrooij** [comment]
https://github.com/terminusdb/terminusdb-store/commit/7c4df74a151a15e8a3e19582045135cf498e506e
:partying_face:
