### ISSUE TITLE
Is terminusdb-store able to handle hundred billion triples for current version?

### ISSUE THREAD

**Issue by leonqli** [terminusdb/terminusdb-store#48]
We have a large triple store (over 50 billion triples) in virtuoso and want to know if terminudb can handle graph of this size or plan to do this. Thanks!

**Comment by luke-feeney** [comment]
Hey @leonqli we certainly plan to be able to handle a graph that size. We haven't fully tested yet on 50 billion triples, but would be interested in helping you to test.

**Comment by leonqli** [comment]
Thanks @luke-feeney! It would be interesting to see some comparison to those known triple stores in performances in handling large graph, such as https://www.w3.org/wiki/LargeTripleStores.

**Comment by spl** [comment]
We're working on it! Thanks for your interest.
