### ISSUE TITLE
License update for rust library

### ISSUE THREAD

**Issue by Immortalin** [terminusdb/terminusdb-store#49]
Can the rust library be changed to MIT? It would be useful for various rust applications outside of databases. The main database would not be affected at all as majority of the database code is in prolog not rust.

**Comment by luke-feeney** [comment]
Hey @Immortalin we have been discussing licenses in the Discord server. Feel free to join (https://discord.gg/CzE5yZdjpr)

I will report back here once we have an outcome

**Comment by luke-feeney** [comment]
hi @Immortalin - we have shifted the license to Apache 2.0 - more on the decision here:

https://terminusdb.com/blog/2020/12/08/we-love-gplv3-but-are-switching-license-to-apache-2-0-terminusdb/
