### ISSUE TITLE
Use sled as a storage backend

### ISSUE THREAD

**Issue by infogulch** [terminusdb/terminusdb-store#72]
https://github.com/spacejam/sled

Sled is an ACID kv-database with LSM/B+Tree performance characteristics written in rust. It's uses prefix encoding for keys which strikes me as very well aligned with terminusdb's storage strategy. It is currently in beta, though some of its caveats wouldn't really apply to tdb currently; e.g. its GC isn't very advanced, but that doesn't matter for tdb since we don't have a GC yet either. :) Sled's readme has a great overview of the project's goals and implementation.

I think it would be interesting to explore using sled as a (/ an alternative) storage backend for terminusdb-store.

**Comment by infogulch** [comment]
Related work: [Stratified B-trees and versioning dictionaries (2011)](https://arxiv.org/abs/1103.4282) ([pdf](https://arxiv.org/pdf/1103.4282.pdf))

**Comment by infogulch** [comment]
I think that sled is pretty cool and might be an interesting long-term strategy, but it's frankly not mature enough to start porting the whole storage backend to it.

I did a shallow review of terminusdb's current storage backend, which appears to simply be files on disk. To me, this indicates that there is a decent amount of low-hanging fruit to be had already. Perhaps a reasonable first step would be to move to SQLite. I think the article [35% Faster Than The Filesystem](https://sqlite.org/fasterthanfs.html) is relevant here. Some quotes:

> SQLite reads and writes small blobs (for example, thumbnail images) 35% faster¹ than the same blobs can be read from or written to individual files on disk using fread() or fwrite().

>  So let your take-away be this: read/write latency for SQLite is competitive with read/write latency of individual files on disk. Often SQLite is faster. Sometimes SQLite is almost as fast. Either way, this article disproves the common assumption that a relational database must be slower than direct filesystem I/O.

**Comment by spl** [comment]
Hi @infogulch! Thanks for the interest and suggestion. Sorry we didn't get back to you sooner.

`terminus-store` has a pretty interesting set of data structures. You can read about them in [Succinct Data Structures and Delta Encoding for Modern Databases](https://terminusdb.com/t/papers/terminusdb-git.pdf). TerminusDB is actually an in-memory database. We only use files for data persistence.

We don't currently feel the need to change our storage backend. Of course, we may always re-evaluate the option later, but, for now, I'll close this issue. Thanks again!

**Comment by infogulch** [comment]
I think that's a reasonable position for the project to take, thanks for your response.

I have studied that paper that you linked and I think that the data structures used in TerminusDB are quite impressive.

To be clear, I'm not advocating for substituting the succinct data structures model with a relational model -- that would be quite silly and would throw away the biggest value that TDB brings to the table. Instead, I'm hinting that storing (succinct data structure) blobs / layers as files on disk is much more risky and error prone than one might guess, and storing the blobs as columns in a SQLite table would be both faster *and* more reliable.

**Comment by spl** [comment]
> To be clear, I'm not advocating for substituting the succinct data structures model with a relational model -- that would be quite silly and would throw away the biggest value that TDB brings to the table. Instead, I'm hinting that storing (succinct data structure) blobs / layers as files on disk is much more risky and error prone than one might guess, and storing the blobs as columns in a SQLite table could be both faster _and_ more reliable. (Hence why I opened this issue on the terminusdb-store repo.)

I see! Thanks for the clarification. If you don't mind me asking, since TerminusDB is append-only, uses highly compressed data, and doesn't write to existing files, how would it be better to store them as blobs in SQLite?

**Comment by infogulch** [comment]
First, sorry if changing my tack from the original issue title and message is a bit confusing. I think high performance disk access will be important to TDB eventually even if it isn't today, and pairing with a high performance file db (like sled) is *fun* to consider from a technology perspective, but it's too early to go down that path.

More importantly, I think reaching for higher reliability than the raw filesystem is a better first step; and I think storing blobs in a sqlite db could offer such an improvement.

---

> TerminusDB is append-only .. and doesn't write to existing files

I agree that TDB's append-only design helps it out here, but even this has a couple exceptions: Needing to discover and delete dead layers created by rollups or unmerged trial branches, and needing to overwrite the root database/label files with the current layer id after an update.

> uses highly compressed data

The fact that layers are highly compressed actually leans in favor of storing as blobs in a db, since this avoids the filesystem overhead of storing another file (some multiple of 4k at minimum).

### In which I hype up SQLite

Ok now for the real question:

> how would it be better to store them as blobs in SQLite?

To which the truly honest answer is "I don't know because I haven't tried it yet," but perhaps I can try to express my intuition for why I think it is worth trying:

SQLite is almost certainly the most reliable and well tested software module you use on a daily basis. I'm confident making this claim because I can probably assume you use a web browser and smartphone, all of which that have shipped in the last decade include and use SQLite. [About SQLite](https://www.sqlite.org/about.html) describes their approach to testing:

> SQLite is [very carefully tested](https://www.sqlite.org/testing.html) prior to every release and has a reputation for being very reliable. Most of the SQLite source code is devoted purely to testing and verification. An automated test suite runs millions and millions of test cases involving hundreds of millions of individual SQL statements and achieves [100% branch test coverage](https://www.sqlite.org/testing.html#coverage). **SQLite responds gracefully to memory allocation failures and disk I/O errors. Transactions are [ACID](https://en.wikipedia.org/wiki/ACID) even if interrupted by system crashes or power failures.**

Some notes: "100% branch test coverage" means that there is a test that executes every side of every machine code branch instruction; yes actually. "Most of the SQLite source code is devoted purely to testing" means 143 KSLOC of C program code and 91911 KSLOC of test code, a factor of 642x. The last couple sentences I bolded is in line with what I mean when I mention "reliability" above. Specifically the things in [I/O Error Testing](https://www.sqlite.org/testing.html#i_o_error_testing) and [Crash Testing](https://www.sqlite.org/testing.html#crash_testing) is what I'm worried about. Some examples I can remember:

* Failing to fsync a file could result in losing writes to it in the event of a system failure, even while another file that was written "afterwards" is correctly synced. (e.g. the database file is updated, but the layer it points to is lost)
* Failing to fsync a *directory* can mean that new files or writes to existing files could be lost or partially lost.
* Overwriting a file can leave the file in an inconsistent state in many different ways
* File locks can be revoked or otherwise lost
* Reading/writing files from a mounted NFS or SMB share can amplify all of the issues mentioned above
* (A very long tail of nightmarish error and recovery edge cases...)

### Approach

Whether any of that convinced you or not, clearly *I've* bought in to the idea that using SQLite as a backing store could be a good idea (actually a common approach in new db engines), but even so I wouldn't just jump in headfirst. So this is how I would approach this:

0. Create goals for failure tolerance and recoverability/rollback capacity. If the TerminusDB project wants to be able to grow to host transactional loads and generally keep customer data safe, this is an important design element to consider.
    * **Q: Do such goals exist explicitly today?**
1. Design tests to measure tolerance of IO errors, crashes, and layer creation performance
    * Something like [unreliablefs - A FUSE-based fault injection filesystem.](https://github.com/ligurio/unreliablefs) could help to simulate IO errors
    * `kill -9` at unfortunate times
    * Run in a VM, kill the whole VM at unfortunate times
    * **Q: Does TerminusDB currently do any similar failure testing?**
2. Implement a SQLiteBackedStore like [FileBackedStore](https://github.com/terminusdb/terminusdb-store/blob/main/src/storage/directory.rs#L19)
3. Compare

I think just items 0-1 would be useful for the TerminusDB project regardless whether you decide to create or test a hypothetical SQLiteBackedStore or not.

**Comment by spl** [comment]
Thanks so much for the wealth of information! Here are a couple thoughts.

I am aware of the reliability of SQLite. I've considered using it several times in various potential personal projects which never came to fruition. Also, I imagine that an SQLite store would be relatively easy to write.

I was not aware of UnreliableFS. It or one of the similar projects listed in its README could be a great resource!

I completely agree that we should develop a better approach to testing fault tolerance and recovery.

We're currently in a period of flux. Plus, I'm rather new here. That said, I appreciate that you took the time to write up your comments, and I will definitely keep them in mind going forward.

Finally, if you decide you're interested enough to dig into the code, we're always happy to have new eyes and more contributions.
